WIDTH = 400
HEIGHT = 800
BULLETS = []
ENEMIES = []
WIDTH_OF_OBJECT = 50
HEIGHT_OF_OBJECT = 50
START_X = WIDTH // 2
START_Y = HEIGHT - 150
DEFAULT_BULLET = 5
SPACESHIPS = ['spaceship.png', 'spcshpv2.png', 'spaceship3.png', 'spaceship4.png']
ALIENS = ['alien.png', 'alien2.png', 'alien3.png', 'alien4.png']
ENEMYRESPAWNTIME = 5000
EVENTSPAWN = 10
SCORE = 0
